all: inclass

# Creates the executable "paint" using the flag "-o".
inclass: inclass.o
	gcc inclass.o -o paint

# Creates the object file "paint.o" using the flag "-c".
inclass.o: inClass.c
	gcc inClass.c -c